### pg 결제 요청
POST {{pg-simulator}}/api/v1/payments
X-USER-ID: 135135
Content-Type: application/json

{
    "orderId": 7,
    "cardType": "SAMSUNG",
    "cardNo": "1234-5678-9814-1451",
    "amount" : 10,
    "callbackUrl": "http://localhost:8080/api/v1/payments/callback"
}

### 결제 정보 확인
GET {{pg-simulator}}/api/v1/payments/20250816:TR:9577c5
X-USER-ID: 135135

### 주문에 엮인 결제 정보 조회
GET {{pg-simulator}}/api/v1/payments?orderId=1351039135
X-USER-ID: 135135

### 콜백
POST {{commerce-api}}/api/v1/payments/callback
Content-Type: application/json

{
    "transactionKey": "20250822:TR:1fe65d",
    "orderId": 1,
    "cardType": "SAMSUNG",
    "cardNo": "1234-5678-9814-1451",
    "amount" : 10,
    "status": "SUCCESS",
    "reason": "결제 성공"
}

### 결제 생성
POST {{commerce-api}}/api/v1/payments
Content-Type: application/json

{
    "userId": "oyy33333",
    "orderId": 2,
    "amount" : 200,
    "paymentMethod": "CARD",
    "cardType": "SAMSUNG",
    "cardNo": "1234-5678-9814-1451"
}
