server:
  shutdown: graceful
  tomcat:
    threads:
      max: 200 # 최대 워커 스레드 수 (default : 200)
      min-spare: 10 # 최소 유지 스레드 수 (default : 10)
    connection-timeout: 1m # 연결 타임아웃 (ms) (default : 60000ms = 1m)
    max-connections: 8192 # 최대 동시 연결 수 (default : 8192)
    accept-count: 100 # 대기 큐 크기 (default : 100)
    keep-alive-timeout: 60s # 60s
  max-http-request-header-size: 8KB

spring:
  main:
    web-application-type: servlet
  application:
    name: commerce-api
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - redis.yml
      - logging.yml
      - monitoring.yml

resilience4j:
  circuitbreaker:
    instances:
      pgRequest:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50 # 실패율이 50% 넘으면 Open
        wait-duration-in-open-state: 10s # Open 상태 유지 시간
        permitted-number-of-calls-in-half-open-state: 2
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 50
      pgDetail:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 50

  retry:
    instances:
      pgRequest:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.io.IOException
          - feign.RetryableException
        fail-after-max-attempts: true
      pgDetail:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.io.IOException
          - feign.RetryableException
        fail-after-max-attempts: true

feign:
  client:
    config:
      default:
        connect-timeout: 1000 # 연결 타임아웃 (ms)
        read-timeout: 6000 # 읽기 타임아웃 (ms)
#        logger-level: full # 로깅 레벨 (none, basic, headers, full)

springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html

cache:
#  스키마 변경시에 버전 업데이트 필요함
  version:
    product: v1

payment:
  callback:
    url: http://localhost:8080/api/v1/payments/callback

pg:
  url: http://localhost:8082


---
spring:
  config:
    activate:
      on-profile: local, test

datasource:
  mysql-jpa:
    main:
      jdbc-url: jdbc:mysql://localhost:3306/loopers
      username: application
      password: application

  redis:
    master:
      host: localhost
      port: 6379
    replicas:
      - host: localhost
        port: 6380

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd

springdoc:
  api-docs:
    enabled: false